<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
   
    <div class="block-content">
    <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Date')) ?></span>
            </strong>
            <div class="box-content">
                <?= $_order->getData('delivery_date') ?>
            </div>
        </div>
    </div>
</div>
