<?php
/** @var \AHT\Eav\Block\Template $block */
?>
<div class="template">
    <h1><?=$block->getName()?></h1>
    <?php
        $post = $block->getPost();
        foreach ($post as $item){
            echo $item['name'];
            echo "<pre>";
            echo $item['content'];
        }
    ?>
</div>
<script>
    window.customConfig = <?=\Zend_Json::encode($block->getPost())?>;
</script>
<div id="md-knockout-example" data-bind="scope:'md-ko-example'">
    <!--   ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
{
"*": {
    "Magento_Ui/js/core/app": {
        "components": {
                "md-ko-example": {
                    "component": "AHT_Eav/js/requirejs-config"
                }
            }
        }
    }
}
</script>
</div>


<!--<div id="component-Id" data-bind="scope:'customComponent'">-->
<!--    <script type="text/x-magento-init">-->
<!--    {-->
<!--        "#component-Id": {-->
<!--            "Magento_Ui/js/core/app": {-->
<!--               "customComponent": {-->
<!--                    "ko": {-->
<!--                        "component": "AHT_Eav/js/requirejs-config",-->
<!--                        "template" : "AHT_Eav/custom",-->
<!--                    }-->
<!--                }-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--    </script>-->
<!--</div>-->
