<?php
/** @var \AHT\Eav\Block\Template $block */
?>

<div class="template">
    <?php
        $post = $block->getTypePost();
        $cat = $block->getName();
    ?>
    <?php foreach($cat as $cats) :?>
     <h1>Bài viết theo danh mục <?=$cats['name']?></h1>
    <?php endforeach;?>
  
    <table>
        <thead>
        <th>ID</th>
        <th>Name</th>
        <th>Content</th>
        <th>Image</th>
        </thead>
       <tbody>
            <?php foreach ($post as $item):?>
                <tr>
                    <td><?=$item['entity_id']?></td>
                    <td><?=$item['name']?></td>
                    <td><?=$item['content']?></td>
                    <td><image width src="http://m243.local/media/eav/index/<?=$item['images']?>" width="500" height="600"/></td>
                </tr>>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
